FROM php:7.3.2-cli

# php extensions install (PostgreSQL => pdo_pgsql pgsql)
RUN apt-get update
RUN apt-get install -y libicu-dev libpng-dev wget unzip git \
      && docker-php-ext-install intl gd mysqli pdo_mysql mbstring

# composer install
RUN curl -sS https://getcomposer.org/installer | php \
      && mv composer.phar /usr/local/bin/composer

# composer setup
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_NO_INTERACTION 1
ENV COMPOSER_HOME /composer
ENV PATH $PATH:/composer/vendor/bin

# install xdebug
RUN pecl install xdebug-beta \
      && docker-php-ext-enable xdebug

# work dir
RUN mkdir /home/workspace
WORKDIR /home/workspace
