version: '3'

services:
  wordpress:
    container_name: wordpress-docker_php73_web
    image: wordpress:php7.3-apache
    ports:
      - "8080:80"
    restart: always
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password
  db:
    container_name: wordpress-docker_mysql_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: password
