version: '3'

services:
  php:
    container_name: php-apache-with-composer
    build: ./.phpenv/php73
    restart: always
    ports:
      - "8000:80"
    links:
      - mysql
      - redis
    volumes:
      - "./html:/var/www/html"
      - "./.conf/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    environment:
      TZ: Asia/Tokyo

  mysql:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password

#  pgsql:
#    container_name: postgresql_db
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: dev
#      POSTGRES_USER: pg_user
#      POSTGRES_PASSWORD: pg_password
#
  redis:
    image: redis:latest
