version: '3'

services:
  php:
    container_name: php-apache-with-composer
    image: php72-apache
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VERSION: 7.2.16
    restart: always
    ports:
      - "8000:80"
#    links:
#      - mysql or pgsql
#      - redis
    volumes:
      - "./html:/var/www/html"
      - "./.conf/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    environment:
      TZ: Asia/Tokyo

#  mysql:
#    container_name: mysql_db
#    image: mysql:5.7
#    restart: always
#    ports: (ローカル接続する場合)
#     - "13306:3306"
#    volumes: (永続化する場合)
#     - "./.mysql:/etc/mysql/conf.d"
#     - "./var/db:/var/lib/mysql"
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: dev
#      MYSQL_USER: dev_user
#      MYSQL_PASSWORD: dev_password
#
#  pgsql:
#    container_name: postgresql_db
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: dev
#      POSTGRES_USER: dev_user
#      POSTGRES_PASSWORD: dev_password
#
#  redis:
#    image: redis:latest
