version: '3'

services:
  mysql:
    container_name: mysql57_23306_db
    image: mysql:5.7
    ports:
      - "23306:3306"
    volumes:
      - "./var/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql23306_db
      MYSQL_USER: mysql23306_user
      MYSQL_PASSWORD: mysql23306_pwd
